apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-agent

spec:
  replicas: 2

  selector:
    matchLabels:
      app: weather-agent

  template:
    metadata:
      labels:
        app: weather-agent

    spec:
      containers:
      - name: weather-app
        image: vamshitelu/weather-agent:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 8000    