apiVersion: v1
kind: Service

metadata:
  name: weather-agent-service

spec:
  type: NodePort

  selector:
    app: weather-agent

  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30080